project:
  type: website

website:
  title: "Alfonso Then"
  description: "Ciencia de datos, analítica de negocios y apuntes"
  site-url: https://dolcos.net
  favicon: assets/img/favicon-32x32.png
  page-navigation: true
  
  navbar:
    pinned: true
    logo: assets/img/favicon-32x32.png
    left:
      - text: Inicio
        icon: person-circle
        href: index.qmd
      - text: Bio
        icon: file-earmark-person
        href: bio.qmd
      - text: Datos
        icon: database
        href: data.qmd
      - text: Modelos
        icon: diagram-3
        href: models.qmd
      - text: Algoritmos
        icon: code-slash
        href: algorithms.qmd  
      - text: Casos
        icon: cash-coin
        href: cases.qmd
      - text: Reportes
        icon: window-sidebar
        href: reports.qmd
      - text: Lecturas
        icon: book
        href: books.qmd
      - text: Cursos
        icon: file-play
        href: courses.qmd
    right:
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/alfonso-then/
      - icon: github
        aria-label: GitHub
        href: https://github.com/dolcos

  page-footer:
      border: true
      left: "&#169; 2024 Alfonso Then"
      right: "Página creada mediante [Quarto](https://quarto.org)"

format:
  html:
    theme: [flatly, assets/styling/theme.scss]
    toc: true
    toc-depth: 4
    pagetitle: "Alfonso Then | {{< meta title >}}"
    page-layout: article
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    highlight-style: a11y
    
    
